package objektwerks

import zio.{Has, Task, ZLayer}
import zio.macros.accessible

@accessible
object ConsoleStore {
  type Store = Has[ConsoleStore.Service]

  trait Service {
    def store(message: Message): Task[Message]
  }

  val live: ZLayer[Any, Nothing, Store] = ZLayer.succeed {
    (message: Message) => Task {
      println(s"[Store] stored: $message")
      message
    }
  }

  // Auto-generated by @accessible
  // def store(message: Message): ZIO[Store, Throwable, Message] = ZIO.accessM(_.get.store(message))
}